import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ProtectedRoute>
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 p-5">
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </ProtectedRoute>
      </body>
    </html>
  );
}
